INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Apple', 0.50, 'Tescos', 14, 'DAYS','NORMAL','FRUIT');
INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Steak', 3.50, 'Butchers', 7, 'DAYS','FRIDGE','MEAT')
INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Fish', 0.50, 'Tescos', 14, 'DAYS','NORMAL','FRUIT');
INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Steak Beef', 3.50, 'Butchers', 7, 'DAYS','FRIDGE','MEAT');


