INSERT INTO RECIPE(RECIPEID, RECIPENAME, RECIPEDURATIONMINS, RECIPEBODY, RATING, DIFFICULTY) VALUES (NEXTVAL('RECIPE_SEQ'), 'MacAndCheese', 5,'blahblah', 'THREE','TWO');
INSERT INTO RECIPE(RECIPEID, RECIPENAME, RECIPEDURATIONMINS, RECIPEBODY, RATING, DIFFICULTY) VALUES (NEXTVAL('RECIPE_SEQ'), 'Mac And Cheese', 50, 'blahblahblah', 'FOUR', 'THREE');

INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Apple', 0.50, 'Tescos', 14, 'DAYS','NORMAL','FRUIT');
INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Steak', 3.50, 'Butchers', 7, 'DAYS','FRIDGE','MEAT')
INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Fish', 0.50, 'Tescos', 14, 'DAYS','NORMAL','FRUIT');
INSERT INTO INGREDIENT(INGREDIENTID, INGREDIENTNAME, PRICE, SHOPNAME, SHELFLIFE, SHELFLIFEUNIT, STORAGETYPE, FOODTYPE) VALUES (NEXTVAL('INGREDIENT_SEQ'), 'Steak Beef', 3.50, 'Butchers', 7, 'DAYS','FRIDGE','MEAT');


INSERT INTO RECIPE_INGREDIENTREQUIREMENTS(RECIPE_RECIPEID,INGREDIENTREQUIREMENTS ,INGREDIENTREQUIREMENTS_KEY ) VALUES( 1, '5tsp' ,1);
INSERT INTO RECIPE_INGREDIENTREQUIREMENTS(RECIPE_RECIPEID,INGREDIENTREQUIREMENTS ,INGREDIENTREQUIREMENTS_KEY ) VALUES( 1, '5tsp' ,2);
INSERT INTO RECIPE_INGREDIENTREQUIREMENTS(RECIPE_RECIPEID,INGREDIENTREQUIREMENTS ,INGREDIENTREQUIREMENTS_KEY ) VALUES( 2, '5tsp' ,2);

INSERT INTO MEALPLAN(MEALPLANID, ESTIMATEDCOST) VALUES (NEXTVAL('MEALPLAN_SEQ'),5.59)
INSERT INTO MEALPLAN(MEALPLANID, ESTIMATEDCOST) VALUES (NEXTVAL('MEALPLAN_SEQ'),51.59)