package com.pgs.Recipe;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import com.pgs.Recipe.model.Recipe;
import com.pgs.Recipe.service.RecipeService;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class RecipeTest {
    
    @Autowired
    private RecipeService recipeService;
    private Recipe retrievedRecipe;
    
    @BeforeEach
    void setUp() {

    }

    @Test
    void test_thatABlankRecipeCanBeCreated(){
        Recipe newRecipe = new Recipe();
        recipeService.createRecipe(newRecipe);
        assertNotEquals(0, newRecipe.getRecipeId());
    }

    @Test
    void test_thatNewRecipesHaveAnAutoGeneratedId(){
        Recipe firstRecipe = new Recipe();
        Recipe secondRecipe = new Recipe();
        recipeService.createRecipe(firstRecipe);
        recipeService.createRecipe(secondRecipe);
        assertEquals(firstRecipe.getRecipeId()+1, secondRecipe.getRecipeId());
    }    
}
