package com.pgs.Recipe;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

import javax.persistence.EntityManager;

import com.pgs.Recipe.model.Difficulty;
import com.pgs.Recipe.model.Ingredient;
import com.pgs.Recipe.model.Rating;
import com.pgs.Recipe.model.Recipe;
import com.pgs.Recipe.service.RecipeService;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class RecipeTest {
    
    @Autowired
    private RecipeService recipeService;

    private Recipe retrievedRecipe;
    
    @BeforeEach
    void setUp() {

    }

    @Test
    void test_thatABlankRecipeCanBeCreated(){
        Recipe newRecipe = new Recipe();
        recipeService.createRecipe(newRecipe);
        assertNotEquals(0, newRecipe.getRecipeId());
    }

    @Test
    void test_thatNewRecipesHaveAnAutoGeneratedId(){
        Recipe firstRecipe = new Recipe();
        Recipe secondRecipe = new Recipe();
        recipeService.createRecipe(firstRecipe);
        recipeService.createRecipe(secondRecipe);
        assertEquals(firstRecipe.getRecipeId()+1, secondRecipe.getRecipeId());
    }

    @Test
    void test_thatARecipeCanBeRetrievedById(){
        retrievedRecipe = recipeService.retrieveById(1);
        assertEquals(1, retrievedRecipe.getRecipeId());
    }

    @Test
    void test_thatARecipeCanBeUpdated() {
        String originalName = "Original";
        String updatedName = "update";
        Recipe originalRecipe = new Recipe(originalName,5,"sdklfjd\nsldfjls",new HashMap<Ingredient,String>(), Rating.FOUR, Difficulty.THREE);
        recipeService.createRecipe(originalRecipe);
        originalRecipe.setRecipeName(updatedName);
        recipeService.updateRecipe(originalRecipe);
        retrievedRecipe = recipeService.retrieveById(originalRecipe.getRecipeId());
        assertEquals(updatedName, retrievedRecipe.getRecipeName());
    }

    @Test
    void test_thatARecipeCanBeRetrievedByName(){
        Recipe expectedRecipe = recipeService.retrieveById(1);
        String recipeName = expectedRecipe.getRecipeName();
        List<Recipe> retrievedRecipes = recipeService.retrieveByName(recipeName);
        assertEquals(expectedRecipe, retrievedRecipes);

    }
}
